<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>roboplan_ros_cpp</name>
  <version>0.6.1</version>
  <description>ROS 2 C++ bindings for the RoboPlan motion planning library.</description>
  <maintainer email="sebas.a.castro@gmail.com">Sebastian Castro</maintainer>
  <maintainer email="eholum@gmail.com">Erik Holum</maintainer>
  <license>MIT</license>

  <url type="website">https://roboplan-ros.readthedocs.io</url>
  <url type="repository">https://github.com/open-planning/roboplan-ros</url>
  <url type="bugtracker">https://github.com/open-planning/roboplan-ros/issues</url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>builtin_interfaces</build_depend>
  <build_depend>nanobind-dev</build_depend>
  <build_depend>python3-dev</build_depend>
  <build_depend>python3-typing-extensions</build_depend>

  <depend>eigen</depend>
  <depend>geometry_msgs</depend>
  <depend>pinocchio</depend>
  <depend>roboplan</depend>
  <depend>rosidl_generator_cpp</depend>
  <depend>sensor_msgs</depend>
  <depend>trajectory_msgs</depend>
  <depend>tf2_eigen</depend>

  <test_depend>ament_index_cpp</test_depend>
  <test_depend>roboplan_example_models</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
