<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>roboplan_ros_franka</name>
  <version>0.6.0</version>
  <description>Franka arm ROS example for RoboPlan.</description>
  <maintainer email="sebas.a.castro@gmail.com">Sebastian Castro</maintainer>
  <maintainer email="eholum@gmail.com">Erik Holum</maintainer>
  <license>MIT</license>

  <url type="website">https://roboplan-ros.readthedocs.io</url>
  <url type="repository">https://github.com/open-planning/roboplan-ros</url>
  <url type="bugtracker">https://github.com/open-planning/roboplan-ros/issues</url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>roboplan</depend>
  <depend>roboplan_example_models</depend>
  <depend>roboplan_ros_examples</depend>
  <depend>xacro</depend>

  <exec_depend>controller_manager</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_broadcaster</exec_depend>
  <exec_depend>joint_trajectory_controller</exec_depend>
  <exec_depend condition="$ROS_DISTRO != humble">parallel_gripper_controller</exec_depend>
  <exec_depend>topic_tools</exec_depend>

  <!-- TODO: Not yet released into ROS 2 Lyrical/Rolling, update when it is. -->
  <exec_depend condition="$ROS_DISTRO != lyrical and $ROS_DISTRO != rolling">mujoco_ros2_control</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
