<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>roboplan_ros_py</name>
  <version>0.6.0</version>
  <description>ROS 2 Python bindings for the roboplan motion planning library.</description>
  <maintainer email="sebas.a.castro@gmail.com">Sebastian Castro</maintainer>
  <maintainer email="eholum@gmail.com">Erik Holum</maintainer>
  <license>MIT</license>

  <url type="website">https://roboplan-ros.readthedocs.io</url>
  <url type="repository">https://github.com/open-planning/roboplan-ros</url>
  <url type="bugtracker">https://github.com/open-planning/roboplan-ros/issues</url>

  <depend>rclpy</depend>
  <depend>builtin_interfaces</depend>
  <depend>trajectory_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>roboplan</depend>
  <depend>roboplan_ros_cpp</depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
