<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>roboplan_ros_examples</name>
  <version>0.6.0</version>
  <description>Examples of using RoboPlan in the ROS ecosystem.</description>
  <maintainer email="sebas.a.castro@gmail.com">Sebastian Castro</maintainer>
  <maintainer email="eholum@gmail.com">Erik Holum</maintainer>
  <license>MIT</license>

  <url type="website">https://roboplan-ros.readthedocs.io</url>
  <url type="repository">https://github.com/open-planning/roboplan-ros</url>
  <url type="bugtracker">https://github.com/open-planning/roboplan-ros/issues</url>

  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <exec_depend>control_msgs</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>roboplan</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
