name: CI

on:
  # Run action on certain pull request events
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

  # Nightly job on default (main) branch
  schedule:
    - cron: '0 0 * * *'

  # Whenever certain branches are pushed
  push:
    branches: [main]

  # On demand from github.com for testing
  workflow_dispatch:

# Ensures that only one workflow runs at a time for this branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: Format
    uses: ./.github/workflows/format.yml

  pixi_build_and_test:
    name: Pixi ROS
    uses: ./.github/workflows/pixi_build_and_test.yml

  pixi_conda_build_and_test:
    name: Pixi Conda RoboPlan
    uses: ./.github/workflows/pixi_conda_build_and_test.yml

  ros_build_and_test:
    name: ROS
    uses: ./.github/workflows/ros_build_and_test.yml
