name: "Pixi Conda RoboPlan Build and Test"

on:
  workflow_call: {}

jobs:
  pixi_conda_roboplan_build_and_test:
    # TODO: Re-enable once the next release of core RoboPlan is released and updated here.
    if: false
    name: ${{ matrix.os }} - Build, test against conda roboplan (${{ matrix.ros_distro }})
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ros_distro: [rolling, lyrical, kilted, jazzy]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        # On Windows, this ensures bash stops at the first failing command.
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.10.0
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          environments: ${{ matrix.ros_distro }}-conda-roboplan
      - name: Build and test against the conda-forge roboplan packages
        run: |
          pixi run -e ${{ matrix.ros_distro }}-conda-roboplan setup
          pixi run -e ${{ matrix.ros_distro }}-conda-roboplan build
          pixi run -e ${{ matrix.ros_distro }}-conda-roboplan test
          pixi run -e ${{ matrix.ros_distro }}-conda-roboplan test-result
