name: "ROS Docker Build and Test"

on:
  workflow_call: {}

jobs:
  ros_build_and_test:
    name: ${{ matrix.ros_distro }} - Build, test ${{ matrix.generate_python_stubs == 'ON' && 'with' || 'without' }} Python stubs
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros_distro: jazzy
            generate_python_stubs: "ON"
          - ros_distro: kilted
            generate_python_stubs: "ON"
          - ros_distro: lyrical
            generate_python_stubs: "ON"
          - ros_distro: rolling
            generate_python_stubs: "ON"

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: roboplan_ros_wrapper
          tags: |
            type=ref,event=branch
            type=ref,event=pr
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .docker/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            ROS_DISTRO=${{ matrix.ros_distro }}
            GENERATE_PYTHON_STUBS=${{ matrix.generate_python_stubs }}
          push: false
          load: true
          cache-from: type=gha,scope=${{ matrix.ros_distro }}
          cache-to: type=gha,mode=max,scope=${{ matrix.ros_distro }}
      - name: Run tests
        run: |
          docker run --rm \
            ${{ steps.meta.outputs.tags }} \
            bash -c "
              colcon test && \
              colcon test-result --verbose
            "
